apiVersion: v1
data:
  ADMIN_USERS: ercohen,lgamliel,mfilanov,ygoldber
  AGENT_DOCKER_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  API_VIP_CONNECTIVITY_CHECK_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  BASE_DNS_DOMAINS: ''
  CONNECTIVITY_CHECK_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  CONTROLLER_IMAGE: quay.io/ocpmetal/assisted-installer-controller@sha256:04bc7de0ad58577952e03291edd0c944a05732b9dbbd58396c3b6c950942928f
  CREATE_S3_BUCKET: 'true'
  DHCP_LEASE_ALLOCATOR_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  ENABLE_AUTH: 'False'
  FIO_PERF_CHECK_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  FREE_ADDRESSES_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  INSTALLER_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer:latest
  INVENTORY_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  JWKS_URL: https://api.openshift.com/.well-known/jwks.json
  NAMESPACE: assisted-installer
  NTP_SYNCHRONIZER_IMAGE: virthost.ostest.test.metalkube.org:5000/localimages/assisted-installer-agent:latest
  OCM_BASE_URL: https://api-integration.6943.hive-integration.openshiftapps.com
  OPENSHIFT_INSTALL_RELEASE_IMAGE_MIRROR: virthost.ostest.test.metalkube.org:5000/localimages@sha256:6ddbf56b7f9776c0498f23a54b65a06b3b846c1012200c5609c4bb716b6bdcdf
  OPENSHIFT_VERSIONS: '{"4.6":{"display_name":"4.6.8","release_image":"virthost.ostest.test.metalkube.org:5000/localimages@sha256:6ddbf56b7f9776c0498f23a54b65a06b3b846c1012200c5609c4bb716b6bdcdf","rhcos_image":"http://virthost.ostest.test.metalkube.org:90/rhcos-4.6.8-x86_64-live.x86_64.iso","support_level":"production"},"4.7":{"display_name":"4.7-pre-release","release_image":"virthost.ostest.test.metalkube.org:5000/localimages@sha256:2419f9cd3ea9bd114764855653012e305ade2527210d332bfdd6dbdae538bd66","rhcos_image":"http://virthost.ostest.test.metalkube.org:90/rhcos-4.6.8-x86_64-live.x86_64.iso","support_level":"beta"}}'
  PUBLIC_CONTAINER_REGISTRIES: virthost.ostest.test.metalkube.org:5000
  SELF_VERSION: virthost.ostest.test.metalkube.org:5000/localimages/assisted-service:latest
  SERVICE_BASE_URL: http://assisted-service-assisted-installer.apps.ostest.test.metalkube.org
  SKIP_CERT_VERIFICATION: 'true'
  HW_VALIDATOR_MIN_DISK_SIZE_GIB: '20'
kind: ConfigMap
metadata:
  labels:
    app: assisted-service
  name: assisted-service-config

